### ISSUE TITLE
 No module named tpms_swig

### ISSUE THREAD

**Issue by crypticalpha** [jboone/gr-tpms#3]
I have successfully built gr-tpms, however when I try to run it, the error below occurs. I checked the "/usr/local/lib/python2.7/dist-packages/tpms/"  folder and verified there is not a folder or module named "tpms_swig". 

cryptic@laptop:~/tpms/gr-tpms/apps$ ./tpms_rx  --source rtlsdr --if-rate 400000 --tuned-frequency 315000000
Traceback (most recent call last):
  File "./tpms_rx", line 37, in <module>
    import tpms
  File "/usr/local/lib/python2.7/dist-packages/tpms/__init__.py", line 44, in <module>
    from tpms_swig import *
ImportError: No module named tpms_swig

**Comment by jboone** [comment]
Not sure what's happening in this case. I would re-run "sudo make install" and see if that helps. If not, re-run the cmake step, but instead use "ccmake" and review the paths visible in the "advanced mode" and make sure they're pointing at the right Python directories.

**Comment by iDoka** [comment]
Hi guy!
I have the same issue on my Ubuntu 14.04 LTS installed as virtual-machine.
I have repeated install step and can't find any swig string in installation log.

After it I try again "cmake .." command and found many warnings like this:

```

$ cmake ..
...
...
...
GNURADIO_PMT_FOUND = TRUE
-- Found SWIG: /usr/bin/swig2.0 (found version "2.0.11") 
CMake Warning (dev) at cmake/Modules/GrSwig.cmake:25 (include):
  Syntax Warning in cmake code at

    /home/adminuser/work/gr-tpms/cmake/Modules/GrPython.cmake:196:44

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  swig/CMakeLists.txt:26 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrSwig.cmake:25 (include):
  Syntax Warning in cmake code at

    /home/adminuser/work/gr-tpms/cmake/Modules/GrPython.cmake:196:92

  Argument not separated from preceding token by whitespace.
Call Stack (most recent call first):
  swig/CMakeLists.txt:26 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at cmake/Modules/GrSwig.cmake:25 (include):
  Syntax Warning in cmake code at

    /home/adminuser/work/gr-tpms/cmake/Modules/GrPython.cmake:196:100
```

Current version of CMake is 2.8.12.2

How to fix this issue?

**Comment by iDoka** [comment]
Hi again!
I have fixed this problem. I just install swig from repository and rerun all install chain:
```
sudo apt-get install swig
```
After that I receive error about "cant open libgnuradio-tpms.so" and fix it with this command:
```
sudo ldconfig
```

Finally I successfuly run tpms_rx, like this:
```
$ tpms_rx --if-rate 500000 --file tpms_rtlsdr.cfile
Using Volk machine: ssse3_64_orc
```
After 2 hours running of tpms_rx nothing happens. CPU load about 0.5%. What I'm doing wrong?

 tpms_rtlsdr.cfile - just test samples with file size about 5MB

**Comment by crypticalpha** [comment]
Thanks for your steps to eliminate the swig error.
What method did you use to create your capture file "tpms_rtlsdr.cfile" mentioned in your post above?

**Comment by iDoka** [comment]
After several hours of googling... I'm kidding.
In two words: based on knowledge of both internal formats (RTL-SDR and input formats for GNU-radio) I created simple script for  MatLAB (or Octave GNU, in case if MATLAB is unavailable):

```
$ cat rtlsdr2gnuradio.m

fid0 = fopen('input.rtlsdr, 'rb');
y = fread(fid0,'uint8=>double');
fclose(fid0);

y = (y-127)./128;

fid1 = fopen('output.cfile','wb');
fwrite(fid1, y, 'float32');
fclose(fid1);
```

Run this for following command:
```
matlab -nosplash -nodesktop -r rtlsdr2gnuradio
```
or
```
octave --silent --persist rtlsdr2gnuradio.m
```

Please, note - this unoptimal script in terms of memory comsumption. By this reason the script applicable only for relatively short files.

**Comment by crypticalpha** [comment]
Hi iDoka,
Thanks for your script above!
Regarding the virtual machine where you have gr-tpms installed: is it running 32-bit or 64-bit Ubuntu 14.04 LTS ?
Thanks in advance.

**Comment by iDoka** [comment]
I preffer 64-bit but I think for python progs and depencies install it doesn't really matter.

**Comment by crypticalpha** [comment]
Would you like to do any consulting to me for getting this project up and running?

**Comment by iDoka** [comment]
I think that I could.
But my investigation and research this tool is stall on the decoding stage - I'm really frustrated what doing with adjustor in GUI.

**Comment by crypticalpha** [comment]
I have temporarily shared my email address in my profile, please email me and we can work out the details.

**Comment by jboone** [comment]
This sounds like build issues that were ultimately resolved with ldconfig. Closing.

**Comment by XgDuan** [comment]
THX @iDoka , the solution helps a lot on other swig-related pkg.

**Comment by Andreas237** [comment]
I know this is belated, but after:
``
sudo apt install swig
``
Then installing  ``FFTW``, ``rtl-sdr``, ``gr-osmosdr``, ``crcmod``, ``watchdog``, ``portaudio``, ``pyaudio``, ``numpy`` without errors.
Followed by ``sudo ldconfig`` I still get the swig import error.  See the screenshot showing ``sudo ldconfig`` immediately followed by a ``swig`` error thrown when trying to run:
``
tpms_rx --source rtlsdr --if-rate 400000 --tuned-frequency 315000000
``

![Linux_Swig_Exception](https://user-images.githubusercontent.com/5612526/55893927-73e27400-5b76-11e9-9467-7bc2ce7210a9.png)

Any advice would be much appreciated!

**Comment by iDoka** [comment]
@Andreas237

Review the ` /etc/ld.so.conf` after  `ldconfig`: You should find proper library directory.
If yes, you can try another approach with LD_PRELOAD_PATH | LD_LIBRARY_PATH, I mean looks like this:
`LD_PRELOAD=/opt/jboone/gr-tpms/lib64/tpms.so; ./tpms_rx`

(please refer other source for precise syntax and guide)
